# ChainC2 Sentinel — Defensive Response Executor
"""DefenseExecutor orchestrates the deterministic execution, verification,

and rollback of DefensePlans generated by DefensivePolicyEngine.
"""

from __future__ import annotations

import logging
import time
from datetime import datetime, timezone
from typing import Any, Optional

from src.protection.handlers.evidence_handler import EvidenceSnapshotHandler
from src.protection.handlers.network_handler import NetworkContainmentHandler
from src.protection.handlers.process_handler import ProcessIsolationHandler
from src.protection.handlers.rpc_handler import RpcFilterHandler
from src.protection.interfaces import BaseMitigationHandler
from src.protection.models import (
    DefenseExecutionRecord,
    DefensePlan,
    DefensePlanStatus,
    MitigationAction,
    MitigationStatus,
    MitigationType,
)
from src.utils.identifiers import generate_event_id

logger = logging.getLogger("chainc2_sentinel.protection.executor")


class DefenseExecutor:
    """Orchestrates deterministic execution, verification, and rollback of defensive mitigations."""

    def __init__(
        self,
        handlers: Optional[dict[MitigationType, BaseMitigationHandler]] = None,
    ) -> None:
        """Initialize executor with mitigation handlers.

        Args:
            handlers: Optional dictionary mapping MitigationType to handler instance.
        """
        self._handlers: dict[MitigationType, BaseMitigationHandler] = handlers or {
            MitigationType.EVIDENCE_PRESERVATION: EvidenceSnapshotHandler(),
            MitigationType.RPC_FILTER: RpcFilterHandler(),
            MitigationType.NETWORK_CONTAINMENT: NetworkContainmentHandler(),
            MitigationType.PROCESS_ISOLATION: ProcessIsolationHandler(),
        }

    def register_handler(
        self,
        mitigation_type: MitigationType,
        handler: BaseMitigationHandler,
    ) -> None:
        """Register or replace a mitigation handler."""
        self._handlers[mitigation_type] = handler

    def get_handler(
        self,
        mitigation_type: MitigationType,
    ) -> Optional[BaseMitigationHandler]:
        """Retrieve the registered handler for a mitigation type."""
        return self._handlers.get(mitigation_type)

    def execute_plan(self, plan: DefensePlan) -> DefenseExecutionRecord:
        """Execute all actions in a DefensePlan in deterministic order.

        Transitions each action from REQUESTED -> EXECUTED -> VERIFIED (or FAILED).

        Args:
            plan: The planned defensive response.

        Returns:
            DefenseExecutionRecord containing the complete audit log.
        """
        start_wall = datetime.now(timezone.utc)
        perf_start = time.perf_counter()

        audit_telemetry: list[dict[str, Any]] = []

        # Scenario A / Negative control: if plan was skipped, record zero mitigation execution
        if plan.status == DefensePlanStatus.SKIPPED:
            perf_elapsed_ms = (time.perf_counter() - perf_start) * 1000.0
            logger.info("DefenseExecutor: Plan %s is SKIPPED. Zero mitigations executed.", plan.plan_id)
            return DefenseExecutionRecord(
                execution_id=generate_event_id(),
                plan=plan,
                overall_success=True,
                actions_executed=0,
                actions_verified=0,
                actions_failed=0,
                started_at=start_wall,
                completed_at=datetime.now(timezone.utc),
                duration_ms=round(perf_elapsed_ms, 3),
                rollback_available=False,
                audit_telemetry=[{
                    "event": "plan_skipped",
                    "reason": "Detection rule did not trigger (benign baseline)",
                    "timestamp": start_wall.isoformat(),
                }],
            )

        executed_count = 0
        verified_count = 0
        failed_count = 0

        # Execute actions sequentially in deterministic order
        for action in plan.actions:
            handler = self._handlers.get(action.mitigation_type)
            if handler is None:
                action.status = MitigationStatus.FAILED
                action.error_message = f"No handler registered for {action.mitigation_type.value}"
                failed_count += 1
                audit_telemetry.append({
                    "action_id": action.action_id,
                    "type": action.mitigation_type.value,
                    "event": "handler_missing",
                    "error": action.error_message,
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                })
                continue

            # Step 1: Execute
            try:
                exec_ok = handler.execute(action)
            except Exception as e:
                exec_ok = False
                action.error_message = f"Execution exception: {type(e).__name__}: {e}"
                logger.error("DefenseExecutor: Exception executing %s: %s", action.mitigation_type.value, e)

            if not exec_ok:
                action.status = MitigationStatus.FAILED
                failed_count += 1
                audit_telemetry.append({
                    "action_id": action.action_id,
                    "type": action.mitigation_type.value,
                    "event": "execution_failed",
                    "error": action.error_message,
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                })
                continue

            executed_count += 1
            audit_telemetry.append({
                "action_id": action.action_id,
                "type": action.mitigation_type.value,
                "event": "executed",
                "timestamp": datetime.now(timezone.utc).isoformat(),
            })

            # Step 2: Verify
            try:
                verify_ok = handler.verify(action)
            except Exception as e:
                verify_ok = False
                action.error_message = f"Verification exception: {type(e).__name__}: {e}"
                logger.error("DefenseExecutor: Exception verifying %s: %s", action.mitigation_type.value, e)

            if not verify_ok:
                action.status = MitigationStatus.FAILED
                failed_count += 1
                audit_telemetry.append({
                    "action_id": action.action_id,
                    "type": action.mitigation_type.value,
                    "event": "verification_failed",
                    "details": action.verification_details,
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                })
                continue

            verified_count += 1
            audit_telemetry.append({
                "action_id": action.action_id,
                "type": action.mitigation_type.value,
                "event": "verified",
                "details": action.verification_details,
                "timestamp": datetime.now(timezone.utc).isoformat(),
            })

        overall_success = (failed_count == 0) and (verified_count == len(plan.actions))
        plan.status = DefensePlanStatus.VERIFIED if overall_success else DefensePlanStatus.FAILED

        perf_elapsed_ms = (time.perf_counter() - perf_start) * 1000.0
        end_wall = datetime.now(timezone.utc)

        logger.info(
            "DefenseExecutor: Plan %s finished with status %s (%d executed, %d verified, %d failed in %.2fms)",
            plan.plan_id,
            plan.status.value,
            executed_count,
            verified_count,
            failed_count,
            perf_elapsed_ms,
        )

        return DefenseExecutionRecord(
            execution_id=generate_event_id(),
            plan=plan,
            overall_success=overall_success,
            actions_executed=executed_count,
            actions_verified=verified_count,
            actions_failed=failed_count,
            started_at=start_wall,
            completed_at=end_wall,
            duration_ms=round(perf_elapsed_ms, 3),
            rollback_available=any(a.is_reversible for a in plan.actions),
            audit_telemetry=audit_telemetry,
        )

    def rollback_plan(self, plan: DefensePlan) -> bool:
        """Roll back all reversible actions in reverse order to restore clean laboratory baseline.

        Args:
            plan: The defense plan to revert.

        Returns:
            True if all reversible actions rolled back successfully, False otherwise.
        """
        all_ok = True
        logger.info("DefenseExecutor: Initiating rollback for plan %s", plan.plan_id)

        # Revert in reverse order of execution
        for action in reversed(plan.actions):
            if not action.is_reversible:
                continue

            handler = self._handlers.get(action.mitigation_type)
            if handler is None:
                continue

            try:
                ok = handler.rollback(action)
                if not ok:
                    all_ok = False
            except Exception as e:
                logger.error("DefenseExecutor: Exception rolling back %s: %s", action.mitigation_type.value, e)
                all_ok = False

        plan.status = DefensePlanStatus.ROLLED_BACK
        logger.info("DefenseExecutor: Rollback complete for plan %s (success=%s)", plan.plan_id, all_ok)
        return all_ok
