# ChainC2 Sentinel — Base Scenario Engine
"""Abstract base scenario class and execution result structures."""

from __future__ import annotations

import abc
import logging
from typing import Any, Optional

from pydantic import BaseModel, ConfigDict, Field

from src.collectors.blockchain_collector import BlockchainTelemetryCollector
from src.collectors.endpoint_collector import SyntheticEndpointCollector
from src.collectors.network_collector import NetworkTelemetryCollector
from src.collectors.rpc_collector import RpcTelemetryCollector
from src.models.events import SentinelEvent, TelemetrySource
from src.normalizer.normalizer import EventNormalizer, EventStore
from src.utils.identifiers import generate_run_id

logger = logging.getLogger("chainc2_sentinel.scenarios")


class ScenarioResult(BaseModel):
    """Encapsulates the execution results and telemetry generated by a scenario."""

    model_config = ConfigDict(extra="forbid")

    scenario_id: str = Field(..., description="Unique identifier of the scenario")
    run_id: str = Field(..., description="Unique execution run ID (UUID4)")
    success: bool = Field(..., description="Whether the scenario executed successfully")
    events: list[SentinelEvent] = Field(
        default_factory=list,
        description="All normalized SentinelEvents produced by the scenario",
    )
    event_counts_by_source: dict[str, int] = Field(
        default_factory=dict,
        description="Count of events grouped by TelemetrySource",
    )
    details: dict[str, Any] = Field(
        default_factory=dict,
        description="Scenario-specific metrics and execution metadata",
    )
    error: Optional[str] = Field(
        default=None,
        description="Error message if execution failed",
    )


class BaseScenario(abc.ABC):
    """Abstract base class for controlled cybersecurity laboratory scenarios."""

    scenario_id: str = "base_scenario"
    scenario_description: str = "Base Scenario"

    def __init__(
        self,
        run_id: Optional[str] = None,
        event_store: Optional[EventStore] = None,
        host: str = "127.0.0.1",
        rpc_proxy_url: str = "http://127.0.0.1:8546",
        upstream_url: str = "http://127.0.0.1:8545",
    ) -> None:
        """Initialize scenario context.

        Args:
            run_id: Optional specific run ID; generated if None.
            event_store: Optional EventStore for file-based JSONL persistence.
            host: Host identifier for telemetry.
            rpc_proxy_url: Client-facing RPC proxy URL.
            upstream_url: Upstream Hardhat node URL.
        """
        self.run_id = run_id or generate_run_id()
        self.event_store = event_store
        self.host = host
        self.rpc_proxy_url = rpc_proxy_url
        self.upstream_url = upstream_url

        self.normalizer = EventNormalizer()

        # Telemetry collectors
        self.endpoint_collector = SyntheticEndpointCollector(
            process_name="chainc2_scenario_client",
            pid=1001,
            host=self.host,
            command_args=["python", "-m", "src.scenarios.runner"],
        )
        self.rpc_collector = RpcTelemetryCollector(
            rpc_endpoint=self.rpc_proxy_url,
            upstream_endpoint=self.upstream_url,
            host=self.host,
        )
        self.blockchain_collector = BlockchainTelemetryCollector(
            chain_id="31337",
            network_name="hardhat",
            host=self.host,
        )
        self.network_collector = NetworkTelemetryCollector(
            host=self.host,
        )

        self._generated_events: list[SentinelEvent] = []

    def record_event(self, event: SentinelEvent, step_name: str) -> SentinelEvent:
        """Tag an event with scenario run metadata and record it."""
        event.metadata["scenario_id"] = self.scenario_id
        event.metadata["run_id"] = self.run_id
        event.metadata["step"] = step_name

        self._generated_events.append(event)
        if self.event_store is not None:
            self.event_store.append(event)

        return event

    @abc.abstractmethod
    def setup(self) -> None:
        """Prepare prerequisite state for the scenario."""
        pass

    @abc.abstractmethod
    def execute(self) -> dict[str, Any]:
        """Run the scenario actions.

        Returns:
            Dictionary of scenario execution details.
        """
        pass

    @abc.abstractmethod
    def teardown(self) -> None:
        """Clean up any temporary resources."""
        pass

    def run(self) -> ScenarioResult:
        """Execute full scenario lifecycle (setup -> execute -> teardown)."""
        self._generated_events.clear()
        details: dict[str, Any] = {}
        success = False
        error_msg: Optional[str] = None

        try:
            logger.info("Starting scenario '%s' (run_id: %s)", self.scenario_id, self.run_id)
            self.setup()
            details = self.execute()
            success = True
        except Exception as exc:
            logger.exception("Scenario '%s' failed: %s", self.scenario_id, exc)
            error_msg = str(exc)
        finally:
            try:
                self.teardown()
            except Exception as teardown_exc:
                logger.error("Error during teardown for '%s': %s", self.scenario_id, teardown_exc)

        # Count events by source
        counts: dict[str, int] = {
            TelemetrySource.ENDPOINT.value: 0,
            TelemetrySource.RPC.value: 0,
            TelemetrySource.BLOCKCHAIN.value: 0,
            TelemetrySource.NETWORK.value: 0,
        }
        for ev in self._generated_events:
            counts[ev.source.value] = counts.get(ev.source.value, 0) + 1

        return ScenarioResult(
            scenario_id=self.scenario_id,
            run_id=self.run_id,
            success=success,
            events=list(self._generated_events),
            event_counts_by_source=counts,
            details=details,
            error=error_msg,
        )
